### ISSUE TITLE
ProductListComponent

### ISSUE THREAD

**Issue by VZhyrytskiy** [dubbha/angular-training#11]
providers: [SortProductsPipe] - Для использования пайпа в классе - ок. Но пайп не зарегистрирован в модуле и при продакшин билде выдает ошибку Cannot determine the module for class SortProductsPipe
Надо добавить еще его и в секцию declaration модуля.

**Comment by dubbha** [comment]
Done
https://github.com/dubbha/angular-training/commit/d85acb5a505097eddfb4ce2b55fda908560c6a89

Есть идеи по поводу таких ворнингов?
```
> ng build --prod

 10% building modules 5/5 modules 0 activeWarning: Can't resolve all parameters for ConfigOptionsService in D:/git/dubbha/angular-training/src/app/shared/config-options.service.ts: (?). This will become an error in Angular v6.x
Warning: Can't resolve all parameters for ConfigOptionsService in D:/git/dubbha/angular-training/src/app/shared/config-options.service.ts: (?). This will become an error in Angular v6.x
Warning: Can't resolve all parameters for GeneratorService in D:/git/dubbha/angular-training/src/app/shared/generator.service.ts: (?). This will become an error in Angular v6.x
Warning: Can't resolve all parameters for GeneratorService in D:/git/dubbha/angular-training/src/app/shared/generator.service.ts: (?). This will become an error in Angular v6.x
```

**Comment by dubbha** [comment]
UPDATE:

Removing `@Injectable` from both services fixed the issue:
https://github.com/dubbha/angular-training/commit/b1224b1b076ac3c0c645dcf6542a6ddff0518d6e

Here's why:
https://github.com/angular/angular/commit/61028fb0e83153357821ef7b52797c641145fa7c
```
we now require the constructor parameters of classes annotated
with `@Injectable` to be statically analyzable by ngc
```
