### ISSUE TITLE
product.component.html

### ISSUE THREAD

**Issue by VZhyrytskiy** [dubbha/angular-training#13]
<input
    class="product__quantity"
    type="number"
    min="1"
    max="9"
    [value]="quantity"
    (change)="onChangeQuantity($event)"
    (blur)="onBlurQuantity($event)"
    [disabled]="!product.isAvailable"
  />
Я бы сначала прописал все в [], а затем в (). Не смешивал бы.

**Comment by dubbha** [comment]
Done.
https://github.com/dubbha/angular-training/commit/d85acb5a505097eddfb4ce2b55fda908560c6a89
