### ISSUE TITLE
Организация приложения

### ISSUE THREAD

**Issue by VZhyrytskiy** [dubbha/angular-training#2]
Ваша организация по типам сущностей подходит для небольших прилоений. Дальше старайтесь организацию делать по функциональности, например корзина, товары, а уже в рамках функциональности по типам.

**Comment by dubbha** [comment]
Реорганизую структуру в соответствии с
https://angular.io/guide/styleguide#application-structure-and-ngmodules

**Comment by dubbha** [comment]
Done
