### ISSUE TITLE
cart.component.html

### ISSUE THREAD

**Issue by VZhyrytskiy** [dubbha/angular-training#3]
Я бы вот эту строчку вынес из темплейта компонента <div *ngIf="cartService.products.length"> и разместил на хост теге, чтобы компонент вообще не создавался, когда нет в нем необходимости

**Comment by dubbha** [comment]
Хост тэг находится в темплейте app.component.html. Для того, чтобы вынести этот ngIf, мне нужно было бы заимпортить cartService в app.component.ts, при этом app.component.ts никак иначе не использует cartService. Действительно есть в этом смысл?
Если все-таки да, сделаю в следующем задании.

**Comment by VZhyrytskiy** [comment]
Это на ваше усмотрение.

**Comment by dubbha** [comment]
В данном случае предпочитаю этого не делать. В аналогичной ситуации в компоненте большей вложенности - учту.
