### ISSUE TITLE
products.module.ts

### ISSUE THREAD

**Issue by VZhyrytskiy** [dubbha/angular-training#5]
exports: [
    // ProductComponent,
    ProductListComponent,
  ],
Посмотрел, что ProductComponent не используется за рамками модуля. Значит его не нужно экспортировать.

**Comment by dubbha** [comment]
Тоже не моё.
У меня вот так:
https://github.com/dubbha/angular-training/blob/task2/src/app/products/products.module.ts
```js
@NgModule({
  imports: [
    CommonModule,
  ],
  declarations: [
    ProductComponent,
    ProductListComponent,
  ],
  exports: [
    ProductListComponent,
  ],
  providers: [
    ProductService,
  ],
})
export class ProductsModule { }
```

**Comment by VZhyrytskiy** [comment]
Закрывайте ишью.
