### ISSUE TITLE
product-list.component.html

### ISSUE THREAD

**Issue by VZhyrytskiy** [dubbha/angular-training#6]
Позабавила кнопка.
<button #buyButton [style.transform]="product.isAvailable ? 'none' : 'rotate(55deg)'" (click)="onBuy(product)">Buy</button>
Если смысл сделать недоступной покупку товара с product.isAvailable = false, то тогда еще стоит поработать со свойством [disabled], иначе купить товар можно.

**Comment by dubbha** [comment]
Это тоже не моё, хотя да, весело. Подозреваю, это был плюс, который становился иксом?

**Comment by VZhyrytskiy** [comment]
Наверное я кому-то не тому ответил. Много пришло проектов сегодня.
