### ISSUE TITLE
cart-item.component.html

### ISSUE THREAD

**Issue by VZhyrytskiy** [dubbha/angular-training#7]
Немного неочевидна работа кнопки
<button (click)="remove()">Remove</button>
Я думал, она полностью товар из корзины удаляет, а она уменшает количество по товару и затем удалет, когда количетсво 0. Может логичнее удалить сразу товар, ведь есть возможность увеличить или уменшить количество другим путем.

**Comment by dubbha** [comment]
Речь о третьей кнопке? С иксом?

```js
<div>
  <span class="cart-item__info">
      {{product.name}}
      [{{product.quantity}} x ${{product.price}} = <strong>${{product.quantity * product.price}}</strong>]
  </span>

  <button class="cart-item__button" (click)="cartService.updateQuantity(product.id, '+')">&#x2795;</button>
  <button class="cart-item__button" (click)="cartService.updateQuantity(product.id, '-')">&#x2796;</button>
  <button class="cart-item__button" (click)="cartService.removeProduct(product.id)">&#x2716;</button>
</div>
```
Она именно удаляет. Использует метод `cartService.removeProduct(product.id)` из сервиса:

```js
  removeProduct(id) {
    this.products = this.products.filter(item => item.id !== id);
  }
```

**Comment by VZhyrytskiy** [comment]
Нет, кажется там есть/была кнопка <button (click)="remove()">Remove

**Comment by dubbha** [comment]
Может, в каком-нибудь соседнем проекте? :)

**Comment by VZhyrytskiy** [comment]
Может быть ошибся.
