### ISSUE TITLE
cart-item.component.ts

### ISSUE THREAD

**Issue by VZhyrytskiy** [dubbha/angular-training#8]
Тут нет особого смысла в параметре, поскольку он не используется внутри обработчика.
@HostListener('mouseenter', ['$event.target']) onmouseenter(element) {
    this.class = 'hover';
  }
  @HostListener('mouseleave', ['$event.target']) onmouseleave(element) {
    this.class = '';
  }

**Comment by dubbha** [comment]
Спасибо, код тоже не мой, но у меня та же ситуация - вместо event.target можно просто использовать this.
Done.

**Comment by dubbha** [comment]
https://github.com/dubbha/angular-training/commit/9cbe432d314d38f65f2ad5aa300c9a81455c22c9
